"""empty message

Revision ID: 14d14da2720a
Revises: 
Create Date: 2018-06-07 14:48:48.682797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d14da2720a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('express',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('taker_id', sa.Integer(), nullable=True),
    sa.Column('ownername', sa.String(length=20), nullable=False),
    sa.Column('starting', sa.String(length=20), nullable=False),
    sa.Column('destination', sa.String(length=10), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=False),
    sa.Column('tips', sa.String(length=15), nullable=False),
    sa.Column('express_id', sa.String(length=20), nullable=False),
    sa.Column('destination_detail', sa.String(length=20), nullable=True),
    sa.Column('weight', sa.String(length=20), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('tips_detail', sa.Text(), nullable=True),
    sa.Column('tele_o', sa.String(length=11), nullable=True),
    sa.Column('wechat_o', sa.String(length=20), nullable=True),
    sa.Column('qq_o', sa.String(length=20), nullable=True),
    sa.Column('tele_t', sa.String(length=11), nullable=True),
    sa.Column('wechat_t', sa.String(length=20), nullable=True),
    sa.Column('qq_t', sa.String(length=20), nullable=True),
    sa.Column('tim_publish', sa.String(length=20), nullable=False),
    sa.Column('time_take', sa.String(length=20), nullable=True),
    sa.Column('time_handover', sa.String(length=20), nullable=True),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.String(length=12), nullable=False),
    sa.Column('wechat_id', sa.String(length=50), nullable=False),
    sa.Column('tele', sa.String(length=15), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('station', sa.Integer(), nullable=True),
    sa.Column('destination', sa.Integer(), nullable=True),
    sa.Column('real_name', sa.String(length=15), nullable=True),
    sa.Column('wechat', sa.String(length=20), nullable=True),
    sa.Column('qq', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('express_user',
    sa.Column('express_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['express_id'], ['express.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('express_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('express_user')
    op.drop_table('user')
    op.drop_table('express')
    # ### end Alembic commands ###
