"""empty message

Revision ID: 17026890bfc2
Revises: 868af5b2e0d9
Create Date: 2018-06-07 17:03:56.486904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '17026890bfc2'
down_revision = '868af5b2e0d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('express', sa.Column('time_publish', sa.String(length=20), nullable=False))
    op.drop_column('express', 'tim_publish')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('express', sa.Column('tim_publish', mysql.VARCHAR(length=20), nullable=False))
    op.drop_column('express', 'time_publish')
    # ### end Alembic commands ###
