"""empty message

Revision ID: 868af5b2e0d9
Revises: 14d14da2720a
Create Date: 2018-06-07 15:39:50.364021

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '868af5b2e0d9'
down_revision = '14d14da2720a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'real_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('real_name', mysql.VARCHAR(length=15), nullable=True))
    # ### end Alembic commands ###
